.\"	$OpenBSD: mdoc.template,v 1.15 2014/03/31 00:09:54 dlg Exp $
.\"
.\" Copyright (c) Hugo Leboeuf Logan Lamouar Aly Sall Aimen Neffati <hugo.leboeuf@viacesi.fr>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\" The following requests are required for all man pages.
.\"
.\" Remove `\&' from the line below.
.Dd $\&Mdocdate$
.Dt NAME SECTION#
.Os
.Sh FONCTIONNEMENT
.Nm exiasaver
Le programme lance un des 3 types d'ecrans de verouillage, le type statique, dynamique ou interactif.
.Sh SYNOPSIS
.\" For a program:  exiasaver [type] [parametre] : Pour le type 1 correspond au statique, 2 pour dynamique et 3 pour interactif
.Nm exiasaver
.Op Fl type Parametre
.Nm
.Ar [type] : 1 pour statique, 2 pour dynamique, 3 pour interactif
.Nm
.Ar [parametre] : Si type 1: Rajouter l'adresse de l'image (Ex:"pokeball.pbm"). Si type 2: Rajouter la resolution ("1","2","3","4"ou"5"). Si type 3: Choisir les coordornees de depart de l'avion de 0 a 80 (Ex:"30x10")
.Nm
.Op Fl stats
.Nm
.Ar [stats] : Lance le menu du programme

.Sh DESCRIPTION
L'Exiasaver est un projet realise en decembre 2016 dans le cadre d'un projet d'etude visant a developper un ecran de verrouillage original pour console linux.